name: Bug report
description: Report a bug
title: "[BUG] "
labels: [ "bug" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is happening?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: false
